//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneJZ.App_Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderPro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPro()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [Display(Name = "Mã Đơn")]
        public int Id { get; set; }
        [Display(Name = "Ngày Tạo")]
        public System.DateTime dateOrder { get; set; }
        [Display(Name = "Họ Tên")]
        public string fullname { get; set; }
        [Display(Name = "Địa Chỉ")]
        public string address { get; set; }
        [Display(Name = "Người Dùng")]
        public string userID { get; set; }
        [Display(Name = "Tổng Đơn")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public Nullable<decimal> totalPrice { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
