//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneJZ.App_Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [Display(Name ="Mã Sản Phẩm")]    
        
        public int Id { get; set; }
        [Display(Name = "Tên Sản Phẩm")]

        public string name { get; set; }
        [Display(Name = "Giá Gốc")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public Nullable<decimal> price { get; set; }
        [Display(Name = "Hình Ảnh")]

        public string image { get; set; }
        [Display(Name = "Mô Tả")]

        public string description { get; set; }
        [Display(Name = "Giảm Giá")]
        [Range(0,100)]
        public int discount { get; set; }
        [Display(Name = "Thành Tiền")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal totalPrice { get; set; }
        [Display(Name = "Thể Loại")]
        public int category { get; set; }
        [Display(Name = "Thể Loại")]
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
